#!/bin/bash

mkdir ca
rm -rf ca/*

# ca

openssl genrsa -out ca/ca.key 4096

openssl req -new -x509 -days 365 -sha512 -key ca/ca.key -out ca/ca.crt

# server

openssl genrsa -out ca/server.key 4096

openssl req -new -sha512 -key ca/server.key -out ca/server.csr

openssl x509 -req -days 365 -sha512 -in ca/server.csr -CA ca/ca.crt -CAkey ca/ca.key -CAcreateserial -out ca/server.crt

# client

openssl genrsa -out ca/client.key 4096

openssl req -new -sha512 -key ca/client.key -out ca/client.csr

openssl x509 -req -days 365 -sha512 -in ca/client.csr -CA ca/ca.crt -CAkey ca/ca.key -CAcreateserial -out ca/client.crt
